name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Make gradlew executable 
      run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: 'cbp-dev_build.jar'
        path: build/libs/cbp-*.jar
